CREATE SCHEMA LA_POC_RAW;
create or replace TABLE ADDRESS (
	ADDRESS_ID NUMBER(38,0) PRIMARY KEY,
	ADDRESS_TYPE VARCHAR(25),
	ADDRESS VARCHAR(100),
	IS_VALID NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9),
	STATE VARCHAR(50)
	
);